---
apiVersion: cascading.securecodebox.io/v1
kind: CascadingRule
metadata:
  name: ssh-audit
  labels:
    securecodebox.io/intensive: light
    securecodebox.io/invasive: non-invasive
    securecodebox.io/speed: fast  # <= 30sec per scan
    securecodebox.io/scantype: ssh-audit
spec:
  scanAnnotations:
    defectdojo.securecodebox.io/product-name: "{{$.hostOrIP}}"
    defectdojo.securecodebox.io/engagement-name: "ssh-audit-{{$.hostOrIP}}"
  matches:
    anyOf:
    - attributes:
        port: 22
        state: open
      category: Open Port
    - attributes:
        service: ssh
        state: open
      category: Open Port
  scanSpec:
    parameters:
    - -p
    - '{{attributes.port}}'
    - '{{$.hostOrIP}}'
    scanType: ssh-audit
