apiVersion: v1
kind: Namespace
metadata:
  name: securecodebox-scans
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nmap
  namespace: securecodebox-scans
spec:
  chart: oci://ghcr.io/securecodebox/helm/nmap
  targetNamespace: securecodebox-scans
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nuclei
  namespace: securecodebox-scans
spec:
  chart: oci://ghcr.io/securecodebox/helm/nuclei
  targetNamespace: securecodebox-scans
  valuesContent: |-
    # using a nuclei image with preloaded templates to avoid downloading them every time
    scanner:
      image:
        repository: docker.io/securecodebox/scanner-nuclei-precooked
        tag: v3.4.2-2025-04-22
    nucleiTemplateCache:
      enabled: false
---
apiVersion: v1
kind: Secret
metadata:
  name: ncrack-lists
  namespace: securecodebox-scans
stringData:
  passwords.txt: |-
    root
    password
    123456
    admin
    postgres
  users.txt: |-
    root
    admin
    postgres
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ncrack
  namespace: securecodebox-scans
spec:
  chart: oci://ghcr.io/securecodebox/helm/ncrack
  targetNamespace: securecodebox-scans
  valuesContent: |-
    scanner:
      image:
        repository: docker.io/j12934/scanner-ncrack
        tag: 0.7
      extraVolumes:
        - name: ncrack-lists
          secret:
            secretName: ncrack-lists
      extraVolumeMounts:
        - name: ncrack-lists
          mountPath: "/ncrack/"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ssh-audit
  namespace: securecodebox-scans
spec:
  chart: oci://ghcr.io/securecodebox/helm/ssh-audit
  targetNamespace: securecodebox-scans
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sslyze
  namespace: securecodebox-scans
spec:
  chart: oci://ghcr.io/securecodebox/helm/sslyze
  targetNamespace: securecodebox-scans
